export default {
  shop: require('./images/shop.png'),
  orangeStar: require('./images/orange-star.png'),
  grayStar: require('./images/gray-star.png'),
  balance: require('./images/balance.png'),
  coins: require('./images/coins.png'),
  eleme: require('./images/eleme.png'),
  luckybag: require('./images/luckybag.png'),
  mobile: require('./images/mobile.png'),
  redbag: require('./images/redbag.png'),
  service: require('./images/service.png'),
  vip: require('./images/vip.png'),
  profile: require('./images/profile.png'),
  order: require('./images/order.png'),
  tabDiscovery: require('./images/tab_discovery.png'),
  tabDiscoverySelected: require('./images/tab_discovery_selected.png'),
  tabOrder: require('./images/tab_order.png'),
  tabOrderSelected: require('./images/tab_order_selected.png'),
  tabShopping: require('./images/tab_shopping.png'),
  tabShoppingSelected: require('./images/tab_shopping_selected.png'),
  tabUser: require('./images/tab_user.png'),
  tabUserSelected: require('./images/tab_user_selected.png')
};
